name: dev-backend

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SharedEditorBackend
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet build
  test-push:
    runs-on: ubuntu-latest
    env:
      SSHPASS: ${{ secrets.SSH_PASSWORD }}
      USER_HOST: root@belelabestia.it
    steps:
      - name: Install sshpass
        run: sudo apt install sshpass
      - name: Transfer file
        run: |
          touch test-file
          sshpass -e ssh -o StrictHostKeyChecking=no $USER_HOST rm -f /var/www/shared-editor/dev/backend/test-file
          sshpass -e scp -o StrictHostKeyChecking=no test-file $USER_HOST:/var/www/shared-editor/dev/backend/
          sshpass -e ssh -o StrictHostKeyChecking=no $USER_HOST rm -f /var/www/shared-editor/dev/backend/test-file
  deploy:
    runs-on: ubuntu-latest
    needs: [test-build, test-push]
    defaults:
      run:
        working-directory: SharedEditorBackend
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish
        run: dotnet publish -c dev -r linux-x64 --self-contained
      - name: Install sshpass
        run: sudo apt install sshpass
      - name: Push to Sissi
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
          USER_HOST: root@belelabestia.it
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no $USER_HOST rm -f /var/www/shared-editor/dev/backend/*
          sshpass -e scp -o StrictHostKeyChecking=no -r bin/dev/net5.0/linux-x64/publish/* $USER_HOST:/var/www/shared-editor/dev/backend/
          sshpass -e ssh -o StrictHostKeyChecking=no $USER_HOST systemctl restart kestrel-shared-editor.dev.service
