name: nightly-backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SharedEditorBackend
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
  test-push:
    runs-on: ubuntu-latest
    env:
      SSHPASS: ${{ secrets.SSH_PASSWORD }}
      USER_HOST: root@belelabestia.it
    steps:
    - name: Install sshpass
      run: sudo apt install sshpass
    - name: Transfer file
      run: |
        touch test-file
        sshpass -e ssh -o StrictHostKeyChecking=no $USER_HOST rm -f /var/www/shared-editor/nightly/backend/test-file
        sshpass -e scp -o StrictHostKeyChecking=no test-file /var/www/shared-editor/nightly/backend/test-file
  deploy:
    runs-on: ubuntu-latest
    needs: [test-build, test-push]
    defaults:
      run:
        working-directory: SharedEditorBackend
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run:  dotnet publish -c Nightly -r linux-x64 --no-self-contained
    - name: Install sshpass
      run: sudo apt install sshpass
    - name: Push to Sissi
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
        USER_HOST: root@belelabestia.it
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no $USER_HOST rm -f /var/www/shared-editor/nightly/backend/*
        sshpass -e scp -o StrictHostKeyChecking=no -r bin/Nightly/net5.0/linux-x64/publish/* root@belelabestia.it:/var/www/shared-editor/nightly/backend/
