name: nightly-backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SharedEditorBackend
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: SharedEditorBackend
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run:  dotnet publish -c Nightly -r linux-x64 --no-self-contained
    - name: Install sshpass
      run: sudo apt install sshpass
    - name: Push to Sissi
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: sshpass -e scp . root@belelabestia.it:/var/www/shared-editor/nightly/backend
      working-directory: SharedEditorBackend/bin/Nightly/net5.0/linux-x64/publish\
